# Dockerfile.reader
FROM python:3.11-slim

WORKDIR /app

# Copy the shell script that contains the Python server logic
COPY serve_log.sh /usr/local/bin/

# Make the script executable
RUN chmod +x /usr/local/bin/serve_log.sh

# Expose the port
EXPOSE 8080

# Command to run the shell script which starts the web server
CMD ["/bin/sh", "/usr/local/bin/serve_log.sh"]