apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-code
data:
  controller.js: |
    const k8s = require('@kubernetes/client-node');
    const axios = require('axios');

    const kc = new k8s.KubeConfig();
    kc.loadFromCluster();

    const customApi = kc.makeApiClient(k8s.CustomObjectsApi);
    const coreApi = kc.makeApiClient(k8s.CoreV1Api);

    const namespace = 'default';

    async function createSite(name, url) {
      console.log(`Creating site for ${url}`);

      const response = await axios.get(url);
      const html = response.data;

      await coreApi.createNamespacedConfigMap(namespace, {
        metadata: { name: `${name}-html` },
        data: { 'index.html': html }
      });

      await coreApi.createNamespacedPod(namespace, {
        metadata: { name: `${name}-pod` },
        spec: {
          containers: [{
            name: 'nginx',
            image: 'nginx:alpine',
            volumeMounts: [{
              name: 'html',
              mountPath: '/usr/share/nginx/html'
            }]
          }],
          volumes: [{
            name: 'html',
            configMap: { name: `${name}-html` }
          }]
        }
      });

      await coreApi.createNamespacedService(namespace, {
        metadata: { name: `${name}-service` },
        spec: {
          selector: { app: name },
          ports: [{ port: 80, targetPort: 80 }]
        }
      });
    }

    async function watchDummySites() {
      const watch = new k8s.Watch(kc);

      watch.watch(
        `/apis/example.com/v1/namespaces/${namespace}/dummysites`,
        {},
        async (type, obj) => {
          if (type === 'ADDED') {
            const name = obj.metadata.name;
            const url = obj.spec.website_url;
            await createSite(name, url);
          }
        },
        err => console.error(err)
      );
    }

    watchDummySites();
