apiVersion: v1
kind: Pod
metadata:
  name: wikipedia-app
spec:
  volumes:
    - name: www-data
      emptyDir: {}

  initContainers:
    - name: init-wikipedia
      image: curlimages/curl:8.4.0
      command:
        - sh
        - -c
        - |
          curl -L https://en.wikipedia.org/wiki/Kubernetes \
            -o /usr/share/nginx/html/index.html
      volumeMounts:
        - name: www-data
          mountPath: /usr/share/nginx/html

  containers:
    # Main container
    - name: nginx
      image: nginx:1.25
      ports:
        - containerPort: 80
      volumeMounts:
        - name: www-data
          mountPath: /usr/share/nginx/html

    # Sidecar container
    - name: wikipedia-sidecar
      image: curlimages/curl:8.4.0
      command:
        - sh
        - -c
        - |
          while true; do
            sleep $((RANDOM % 600 + 300))
            PAGE=$(date +%s)
            curl -L https://en.wikipedia.org/wiki/Special:Random \
              -o /usr/share/nginx/html/random-$PAGE.html
          done
      volumeMounts:
        - name: www-data
          mountPath: /usr/share/nginx/html
